# 공통 설정
server:
  port: ${PORT}
spring:
  profiles:
    default: local
  config:
    import: application-algo.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expire-length: ${ACCESS_TOKEN_EXPIRE}
      refresh-token:
        expire-length: ${REFRESH_TOKEN_EXPIRE}
naver:
  url:
    search:
      book: https://openapi.naver.com/v1/search/book.json
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}

# 로컬 프로파일 설정
---
spring:

  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?&rewriteBatchedStatements=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URI}
logging.level:
  tracer:
    TRACE
  com.bombombom: ${LOG_LEVEL}
  org.springframework.security: TRACE
  org.hibernate.SQL : debug
  org.hibernate.orm.jdbc.bind: trace

# 테스트 프로파일 설정
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${TEST_MYSQL_DATABASE}?&rewriteBatchedStatements=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  elasticsearch:
    uris: ${TEST_ELASTICSEARCH_URI}
logging.level:
  tracer:
    TRACE